# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[('resources', 'resources')],
    hiddenimports=[
        'PySide6.QtWebEngineWidgets',
        'PySide6.QtWebEngineCore',
        'PySide6.QtWebChannel',
        'rawpy',
        'exiftool',
        'src.map_widget',
        'src.track_service',
        'src.track_match_dialog',
        'src.ai_service',
        'src.ai_settings_dialog',
        'src.ai_guesser_dialog',
        'src.auto_tagger',
        'src.backup_manager',
        'src.folder_dialog',
        'src.photo_grid',
        'src.photo_item',
        'src.photo_manager',
        'src.photo_preview',
        'src.save_progress_dialog',
        'src.session_manager',
        'src.thumbnail_cache',
        'src.workers',
        'src.app',
        'resources.theme',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='GeoTagStudioPRO',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='NONE',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='GeoTagStudioPRO',
)
